import api from "../../services/api";

import Head from "next/head";
import Image from "next/image";

//Components
import Header from "../../components/header";
import Footer from "../../components/footer";
import Contact from "../../components/contact";
import Navbar from "../../components/navbar";

export async function getServerSideProps(context) {
  const category = context.query.slug;
  const slug = context.query.product;

  const res = await api.get(`/products?category=${category}&product=${slug}`);
  const categories = await api.get(`/category`);

  return {
    props: {
      product: res.data,
      categories: categories.data,
    },
  };
}

export default function SingleProduct({ product, categories }) {
  console.log(product);

  if (product.error) {
    return (
      <div className="tw-h-[100vh] tw-flex tw-items-center tw-flex-col tw-justify-center tw-w-full">
        <h1>
          O Produto selecionado não existe ou possui informações de nome e
          categoria incorretos!
        </h1>
        <p>CÓDIGO DO ERRO: 404 Not found</p>
      </div>
    );
  }
  return (
    <div className="">
      <Head>
        <title>GGL Móveis de Aço | {product.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="tw-mt-[140px] tw-mb-[100px] tw-relative">
        <Navbar categories={categories} />
        <section
          id="product-wrapper"
          className="tw-flex tw-mb-[150px]  tw-justify-between tw-w-[85%] tw-ml-[15%] tw-px-[5%]"
        >
          <div className="tw-w-[50%] ">
            <div id="principal-image">
              <img src={product.images[0]} />
            </div>
            <div id="carousel-images"></div>
          </div>
          <div className="tw-w-[50%]">
            <h1 className="tw-text-[38px]">{product.name}</h1>
            <p>{product.description}</p>
            <h1 className="tw-text-[32px] tw-mt-[50px]">Medidas</h1>
            <table className="tw-font-light tw-w-full">
              <tr className="">
                <th className="tw-w-[50%] tw-border-[1px] tw-border-black tw-py-[10px] tw-px-[15px] tw-text-start tw-font-light">
                  Altura
                </th>
                <th className="tw-w-[50%] tw-border-[1px] tw-border-black tw-py-[10px] tw-px-[15px] tw-text-start tw-font-light">
                  {product.scale.height}
                </th>
              </tr>
              <tr>
                <th className="tw-w-[50%] tw-border-[1px] tw-border-black tw-py-[10px] tw-px-[15px] tw-text-start tw-font-light">
                  Largura
                </th>
                <th className="tw-w-[50%] tw-border-[1px] tw-border-black tw-py-[10px] tw-px-[15px] tw-text-start tw-font-light">
                  {product.scale.width}
                </th>
              </tr>
              <tr>
                <th className="tw-w-[50%] tw-border-[1px] tw-border-black tw-py-[10px] tw-px-[15px] tw-text-start tw-font-light">
                  Profundidade
                </th>
                <th className="tw-w-[50%] tw-border-[1px] tw-border-black tw-py-[10px] tw-px-[15px] tw-text-start tw-font-light">
                  {product.scale.depth}
                </th>
              </tr>
              <button
                type="submit"
                className="tw-bg-blue tw-mt-[30px] tw-text-white tw-w-[240px] tw-h-[50px] hover:tw-bg-white hover:tw-border-blue hover:tw-border-[1px] hover:tw-text-blue tw-transition-300"
              >
                Fazer Orçamento
              </button>
            </table>
          </div>
        </section>
        <Contact />
      </main>
      <Footer />
    </div>
  );
}
