import api from "../../services/api";

import Head from "next/head";
import Image from "next/image";

//Components
import Header from "../../components/header";
import Footer from "../../components/footer";
import Contact from "../../components/contact";
import Navbar from "../../components/navbar";

export async function getStaticProps() {
  const res = await api.get("/category?category=all");

  return {
    props: {
      categories: res.data,
    },
    revalidate: 5,
  };
}

export default function Produtos({ categories }) {
  return (
    <div>
      <Head>
        <title>GGL Móveis de Aço | Categorias</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="tw-mt-[120px]">
        <section className="tw-px-[20px] tw-flex-col md:tw-flex-row tw-flex tw-items-center">
          <div className="tw-w-full">
            <h1 className="tw-text-[35px] tw-mb-[10px] tw-text-center">
              PRODUTOS
            </h1>
            <p className="tw-text-center">
              Produtos da mais excelente qualidade para sua empresa.
            </p>
          </div>
          {/* <div className="tw-w-full md:tw-w-[50%] tw-flex tw-justify-center">
            <img src="/assets/banners/banner1.png" className="" />
          </div> */}
        </section>
        <section className="tw-px-[20px] tw-flex tw-justify-center tw-flex-wrap tw-gap-y-[80px] tw-gap-x-[40px] tw-mt-[80px] tw-mb-[100px]">
          {categories.categoryArray.map((category, i) => (
            <a
              key={i}
              href={`/produtos/${category.slug}?product=${category.products[0].slug}`}
              className="tw-max-w-[350px] tw-w-full"
            >
              <img
                src={category.image}
                className="tw-h-[300px] tw-object-contain tw-w-full"
              />
              <div className="tw-mt-[20px]">
                <h1 className="tw-text-[22px]">{category.name}</h1>
                <p>{category.description}</p>
              </div>
            </a>
          ))}
        </section>
        <Contact />
      </main>
      <Footer />
    </div>
  );
}
