import Head from "next/head";
import Image from "next/image";

//Components
import Header from "../components/header";
import Footer from "../components/footer";
import Contact from "../components/contact";

//Carousel
import AliceCarousel from "react-alice-carousel";
import "react-alice-carousel/lib/alice-carousel.css";

//player
import ReactPlayer from "react-player";

//icons
import { AiOutlineCloudDownload } from "react-icons/ai";

//api
import api from "../services/api";

const banners = [
  <div className="tw-flex tw-items-center tw-justify-around">
    <div className="tw-flex tw-flex-col">
      <h1 className="tw-text-[30px] tw-mb-[20px]">Ármarios</h1>
      <p className="tw-w-[300px]">
        Móveis de excelente qualidade e resistência e perfeito acabamento para
        harmonizar seu espaço.
      </p>
      <a
        href=""
        className="tw-border-blue tw-text-blue tw-py-[10px] tw-mt-[20px] tw-transition-300 hover:tw-bg-blue hover:tw-text-white tw-border-[1px] tw-w-[300px] tw-text-center"
      >
        Saiba mais
      </a>
    </div>
    <div>
      <img src="/assets/banners/armarios_home.png" className="tw-w-[400px] " />
    </div>
  </div>,
  <div className="tw-flex tw-items-center tw-justify-around">
    <div className="tw-flex tw-flex-col">
      <h1 className="tw-text-[30px] tw-mb-[20px]">Arquivos</h1>
      <p className="tw-w-[300px]">
        Móveis de excelente qualidade e resistência e perfeito acabamento para
        harmonizar seu espaço.
      </p>
      <a
        href=""
        className="tw-border-blue tw-text-blue tw-py-[10px] tw-mt-[20px] tw-transition-300 hover:tw-bg-blue hover:tw-text-white tw-border-[1px] tw-w-[300px] tw-text-center"
      >
        Saiba mais
      </a>
    </div>
    <div>
      <img src="/assets/banners/armarios_home.png" className="tw-w-[400px] " />
    </div>
  </div>,
];

const videos = [
  <div className="tw-flex tw-w-full tw-justify-center">
    <ReactPlayer url="https://www.youtube.com/watch?v=ysz5S6PUM-U" />
  </div>,
  <div className="tw-flex tw-w-full tw-justify-center">
    <ReactPlayer url="https://www.youtube.com/watch?v=ysz5S6PUM-U" />
  </div>,
];

export async function getStaticProps() {
  const res = await api.get("/category");

  return {
    props: {
      categories: res.data,
    },
    revalidate: 5,
  };
}

export default function Home({ categories }) {
  console.log(categories);
  return (
    <div className="">
      <Head>
        <title>GGL Móveis de Aço | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="tw-mt-[160px] tw-mb-[130px]">
        <section>
          <AliceCarousel items={banners} />
        </section>
        <section className="tw-px-[5%] tw-my-[100px]" id="catalogo">
          <small className="tw-text-blue">CATÁLOGO</small>
          <h1 className="tw-text-[30px]">Nosso catálogo</h1>
          <div className="tw-flex tw-items-center tw-justify-around tw-mt-[40px]">
            <img src="/assets/banners/catalogo.png" className="tw-w-[300px]" />
            <div>
              <p className="tw-w-[360px] tw-mb-[30px]">
                Baixe nosso catálogo para ter acesso a informações técnicas
                sobre nossos produtos.
              </p>
              <a href="" className="tw-flex tw-items-center hover:tw-underline">
                <AiOutlineCloudDownload />
                <span className="tw-ml-[10px]">Baixar catálogo</span>
              </a>
            </div>
          </div>
        </section>
        <section className="tw-px-[5%]">
          <small className="tw-text-blue">CONTEÚDO</small>
          <h1 className="tw-text-[30px]">Vídeos</h1>
          <div className="tw-w-full tw-flex tw-justify-center tw-mt-[30px]">
            <div className="tw-w-[80%] ">
              <AliceCarousel items={videos} />
            </div>
          </div>
        </section>
        <Contact />
      </main>
      <Footer />
    </div>
  );
}
