import Head from "next/head";
import { useState, useEffect } from "react";
import Header from "../components/header";
import Footer from "../components/footer";
import Contact from "../components/contact";

export default function Videos() {
  const [window, setWindow] = useState(false);
  useEffect(() => {
    setWindow(true);

    let query = location.hash;
    if (query !== "") {
      location.replace(`/${query}`);
    }
  });

  const videos = [
    {
      name: "Montagem de Gondola Central",
      id: "nPwJHr-P7ek",
    },
    {
      name: "Montagem de Estante de Armazenamento",
      id: "Wr1YHpplRbE",
    },
    {
      name: "Montagem da Estante Biblioteca",
      id: "r7wG3CCayP0",
    },
    {
      name: "Estante Biblioteca com Sistema de Encaixe",
      id: "_l0TqQY2HPk",
    },
  ];

  return (
    <div>
      <Head>
        <title>GGL Móveis de Aço | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {window && (
        <main className="tw-mt-[110px] tw-mb-[130px] tw-max-w-[1920px] tw-mx-auto tw-pt-[30px]">
          <h1 className="tw-text-[30px] tw-text-center">Vídeos</h1>
          <section className="tw-px-[20px] tw-pt-[30px] tw-flex tw-justify-center tw-items-center tw-flex-wrap tw-gap-[20px] tw-mb-[120px] tw-max-w-[1280px] tw-w-full tw-mx-auto">
            {videos.map((v, i) => (
              <a
                key={i}
                href="#"
                className="tw-flex tw-flex-col tw-items-center"
              >
                <div className="tw-relative tw-overflow-hidden tw-aspect-video tw-w-full sm:tw-w-[400px]">
                  <iframe
                    className="tw-aspect-video tw-top-0 tw-left-0 tw-right-0 tw-bottom-0 tw-w-full tw-h-full"
                    src={`https://www.youtube.com/embed/${v.id}`}
                    title={v.name}
                    frameBorder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    allowFullScreen
                  ></iframe>
                </div>
              </a>
            ))}
          </section>

          <Contact />
        </main>
      )}
      <Footer />
    </div>
  );
}
